name: Assemble module

on:
  workflow_call:
    inputs:
      module:
        description: 'Module to run'
        required: true
        type: string
      push-apk:
        description: 'Push artifact'
        required: false
        type: boolean
        default: false
jobs:
  assemble:
    uses: ./.github/workflows/gradle-task.yml
    with:
      module: ${{ inputs.module }}
      task: assemble
      task-name: Assemble ${{inputs.module}}
      push-apk: ${{ inputs.push-apk }}
