on:
  workflow_call:
    inputs:
      module:
        description: 'Module to run'
        required: true
        type: string
jobs:
  unit-test:
    uses: ./.github/workflows/gradle-task.yml
    with:
      module: ${{ inputs.module }}
      task: test
      task-name: Run Unit Tests
