name: Verify Checkout

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    types: [ opened, synchronize, reopened ]
    branches: [ master, "bugfix/*", "feature/*", "release/*" ]
    paths:
      - 'checkout/**'
      - 'buildSrc/**'
      - 'build.gradle.kt'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify-module:
    uses: ./.github/workflows/verification-flow.yml
    secrets: inherit
    with:
      module: checkout
      run-ktlint: true
